steps:
  # 1) Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/cloud-run-app',
      '.'
    ]

  # 2) Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/cloud-run-app'
    ]

  # 3) Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run',
      'deploy',
      'cloud-run-app',
      '--image',
      'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/cloud-run-app',
      '--region',
      'us-central1',
      '--platform',
      'managed',
      '--allow-unauthenticated'
    ]

# Optionally, specify images for build output references
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/my-repo/cloud-run-app'

options:
  logging: CLOUD_LOGGING_ONLY
